packages:
  - packages/*
  - examples/*
  - website

catalog:
  playwright: ^1.59.1
  "@playwright/test": ^1.59.1

allowBuilds:
  "@prisma/engines": true
  better-sqlite3: true
  esbuild: true
  msw: false
  prisma: true
  sharp: true
