name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write # Required for OIDC
  contents: write # Required for changesets to push commits
  pull-requests: write # Required for changesets to create PRs

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6.1.0

      - uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          registry-url: "https://registry.npmjs.org"
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Release Pull Request or Publish
        uses: changesets/action@v2.1.2
        with:
          publish-script: pnpm run release
